spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/baeldung
          jwk-set-uri: http://localhost:8081/auth/realms/baeldung/protocol/openid-connect/certs
